# Site settings
title: B치lint Holl칩sy
#description:
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://hollosy.github.io/"
markdown: kramdown

# User settings
username: B치lint Holl칩sy
#user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Data Scientist
email: hollosylb@gmail.com
#twitter_username: lorem_ipsum
github_username:  hollosy
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
